### ISSUE TITLE
info 

### ISSUE THREAD

**Issue by devds** [adix64/Freeform3DCurveEditor#1]
Hi, I have compiled without errors , but when I launch the application, it ceashes.
In debug mode , I get 
![debug](https://user-images.githubusercontent.com/4224920/191796262-f5848922-2356-4880-9fbb-8ce9ff8b42b2.png)
Can you help me to compile correctly?

**Comment by adix64** [comment]
Hey man! Thanks so much for downloading this repo! Unfortunately at the time I was very new to git and didn't realize that the gitignore implied missing files. I uploaded them now, thank God I found them on a dusty hard drive.
Just clone the repo again and it should work out of the box.
Feel free to use this code for anything except doing harm to anyone.
Cheers!
